profile/legacy_profile.go

Extend regexp for matching legacy growth profiles

---

internal/graph/graph.go

This eliminates non-determinism on some of the generated reports.

Make Node sorting check all Info fields

---

internal/graph/graph.go
internal/report/report.go
internal/report/report_test.go

When using the call_tree option and generating a graph for kcachegrind,
it will merge back nodes that are distinct on the tree, producing some
confusing results. Add a suffix so that these entries are kept separate.
This addresses the problem described in
http://yosefk.com/blog/how-profilers-lie-the-cases-of-gprof-and-kcachegrind.html ,
particularly the summary "Choosing a profiler is hard" section.

Disambiguate names for kcachegrind under the call_tree option

---

internal/driver/interactive.go
internal/driver/interactive_test.go

Support commands like "top10" or "web5"

Add support for abbreviated commands on interative command like

---

internal/symbolizer/symbolizer.go
internal/symbolizer/symbolizer_test.go

Even after local symbolization completes successfully we should
call remote symbolization in case there are some mapping that couldn't
be symbolized otherwise.
Add some tests to ensure both local and symbolz symbolization are called.

Ensure symbolz is called after local symbolization

---

profile/encode.go
profile/legacy_profile.go
profile/profile.go
profile/proto.go

Should have no functional changes

Misc changes suggested by readability review

---

internal/graph/graph_test.go

It seems these do not need to be exported.

Unexport test data structures and fields

---

profile/profile.go

Some profile handlers will split mappings into multiple adjacent
entries. This interferes with pprof when overriding the main binary.
Currently there is code that attempts to combine these mappings, but
it fails if the mapping offsets aren't available. Add a check to
combine them in that situation.

Combine adjacent mappings even if offsets are unavailable

---

profile/legacy_profile.go

If the memory map is generated by logging routines such as glog, they
may include some initial text which confuses the parsing of legacy
mappings. The initial text is the same for all mapping entries,
so detect it on the proc map sentinel and remove it from the mapping
entries.
As part of this will remove the unnecessarily generic sectionTrigger, since
the only section we recognize with a trigger is the memory map.

Handle memory maps generated by logging

---

profile/legacy_profile.go
profile/legacy_profile_test.go

A previous commit attempted to handler mappings produces using the glog
package by matching the column on which the sentinel was found.
However, some tools generate the mapping using a single log entry,
where the prefix appears only on the first line.
Instead of matching by column, use a regexp to identify and match
prefixes introduced by the glog package.

Remove logging entries using a regexp

---

profile/profile.go

Often profile handlers return no data, and pprof currently
returns "profile format unrecognized", which confuses users
and sends them on a wild goose chase.
Print a more explicit "empty input file" error message.

Explicitly return error for empty input files

---

internal/driver/fetch.go
profile/legacy_profile.go

These are the remaining relevant commits identified from the Go distribution.
The others in Hana's list are either already applied or not applicable.

Merge commits from Go distribution

---

driver/driver.go

formatting-only change -- merging

gofmt recent changes

---

README.md

Add GOPATH reminder on README.md

---

internal/measurement/measurement.go
internal/measurement/measurement_test.go

This fixes #137 (but not #136, this will come separately once we decide
what we want to do if anything).

Add support for terabyte and petabyte memory units.

---

internal/driver/fetch_test.go

Skip TestHttpsInsecure test on nacl

---

internal/driver/testdata/pprof.cpu.flat.functions.call_tree.dot
internal/driver/testdata/pprof.cpu.flat.functions.dot
internal/graph/dotgraph.go
internal/graph/dotgraph_test.go
internal/graph/testdata/compose2.dot
internal/graph/testdata/compose3.dot
internal/graph/testdata/compose4.dot
internal/graph/testdata/compose5.dot
internal/graph/testdata/compose6.dot

Support URL link from the legend box.

---

appveyor.yml

Addresses #149 
* Added appveyor.yml

Enable integration with Appveyor

---

internal/driver/driver.go
internal/driver/driver_test.go
internal/driver/testdata/pprof.contention.flat.addresses.dot.focus.ignore
internal/driver/testdata/pprof.cpu.cum.lines.text.focus.hide
internal/driver/testdata/pprof.cpu.cum.lines.text.hide
internal/driver/testdata/pprof.cpu.cum.lines.text.show
internal/driver/testdata/pprof.cpu.cum.lines.topproto.hide
internal/driver/testdata/pprof.heap.cum.lines.tree.focus
internal/driver/testdata/pprof.heap.cum.relative_percentages.tree.focus
internal/driver/testdata/pprof.heap.flat.files.text.focus
internal/driver/testdata/pprof.heap.flat.inuse_space.dot.focus
internal/driver/testdata/pprof.heap.flat.inuse_space.dot.focus.ignore
internal/driver/testdata/pprof.heap.flat.lines.dot.focus
internal/driver/testdata/pprof.heap_alloc.flat.alloc_space.dot
internal/driver/testdata/pprof.heap_alloc.flat.alloc_space.dot.focus
internal/driver/testdata/pprof.heap_alloc.flat.alloc_space.dot.hide
internal/report/report.go
internal/report/report_test.go

Updated legend to show settings related to the options show, hide, focus, ignore, tagfocus, tagignore, tagshow, and taghide

Update legend to show show/hide/focus/ignore settings

---

internal/driver/cli.go
internal/driver/commands.go
internal/driver/driver.go
internal/driver/driver_test.go
internal/driver/fetch.go
internal/driver/fetch_test.go
internal/driver/testdata/cppbench.contention
internal/driver/testdata/cppbench.small.contention
internal/driver/webhtml.go
internal/driver/webui.go
internal/driver/webui_test.go
profile/merge.go
profile/profile_test.go

Detailed list of changes:
* Since the list of actions is now long, move it into
an action box that is displayed only when applicable.
* Display help messages when hovering over action buttons.
* Hitting return in the search box invokes "focus" action.
* Cleaned up stale css entries.
I have attached one of the resulting pages to see what things look like easily.  It is static, so won't allow navigation to other pages, but should be interactive enough.
[benchcpu.zip](https://github.com/google/pprof/files/1151238/benchcpu.zip)

Added peek command to web interface.

---

internal/driver/webui_test.go

Skip TestNewListenerAndURL on NaCl

---

fuzz/fuzz_test.go

Skip Fuzz TestParseData on Nacl

---

internal/measurement/measurement.go
internal/measurement/measurement_test.go

fixed year unit conversion

---

internal/driver/webhtml.go

Limit width of name column to prevent very long names from crowding out the inline column.

---

internal/driver/webhtml.go

This allows right-click/middle-click etc. to work properly.
This one is only html/css/javascript changes, so presumably
@josef-jelinek is the best reviewer.

Change menu buttons to links.

---

internal/driver/webhtml.go
internal/driver/webui.go
internal/driver/webui_test.go
internal/report/report.go

Just Javascript changes, so again for @josef-jelinek

Make top table sortable by column

---

internal/driver/cli.go
internal/driver/commands.go
internal/driver/driver_test.go
internal/driver/fetch.go
internal/driver/testdata/pprof.cpu.comments

Add flag to append a comment to a profile.

---

internal/driver/webui_test.go
profile/profile.go
profile/profile_test.go

Added some multi-threaded tests that allow the race detector
to detect race conditions in pprof internals.

Make Profile copying and encoding thread-safe.

---

internal/symbolz/symbolz.go
internal/symbolz/symbolz_test.go

https://github.com/golang/go/issues/22483

Locate symbol endpoints with deeper paths

---

internal/driver/driver.go
internal/driver/webui.go
internal/driver/webui_test.go

Fixes #258. Reported in https://github.com/golang/go/issues/22651.

Do not attempt to open the browser in tests.

---

internal/driver/webhtml.go

Indenting the JS and HTML sources for readability

Indenting the JS and HTML sources for readability

---

internal/driver/webhtml.go

updating search input element id on flame graph view. fixes #287.

fix: updating search input element id. fixes #287

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.md
internal/driver/webhtml.go

Addresses a couple of style errors and typos identified by linters.

Fix style problems

---

profile/merge.go
profile/profile_test.go

Fix panic on merge when one profile missing mappings

---

internal/driver/interactive.go
internal/driver/interactive_test.go
internal/proftest/proftest.go

Clarify error messages in interactive for groups

---

internal/elfexec/elfexec.go

Remove duplicate word "the"

---

internal/driver/fetch_test.go
internal/proftest/proftest.go

This was reported / noted in #328.

Make pprof driver tests less noisy

---

.travis.yml
README.md

Stop supporting Go older than 1.9

---

profile/legacy_java_profile.go
profile/testdata/java.contention.string

Fix wrong unit type for contention count when parsing legacy Java profiles

---

proto/profile.proto

Not sure about the year for the license.

add license to profile.proto

---

internal/driver/driver_focus.go
internal/driver/driver_test.go

Allow tagfocus expressions to have explicit +/- prefix

Support sign in tagfocus

---

profile/profile_test.go

This is similar to such flag in driver_test.go and dotgraph_test.go.
I had this change locally for some time, would like to check this in.

Add -update flag that can be used to update golden files.

---

internal/driver/commands.go
internal/driver/interactive.go

cli: add 'q' as an alias for 'quit'

---

internal/graph/graph.go

chore: fix typo

---

profile/merge.go

Closes https://github.com/google/pprof/issues/589

profile: Extend merge API comment in regards to associativity

---

internal/graph/dotgraph.go

Providing score -1 actually returns green not red. Conversely, 1 returns red.
See lines 375 and 378. r = 1 + saturation*score is r = 1 - saturation if score == -1. Thus, r decreases and g < r.

Fixing comment in dotColor function.

---

internal/driver/webhtml.go
internal/driver/webui.go

Updated this PR https://github.com/google/pprof/pull/617 with the style for the link

feat(ui): add link to download profile to the UI

---

doc/README.md

doc: clarify graph view docs to note negative values appear in profile comparison

---

internal/measurement/measurement.go

Make unit types a list. When and if needed, next step can be making it
possible for select pprof clients (such as internal Google one) append
additional types.

Generalize the unit support in pprof a bit further.

---

.github/workflows/ci.yaml
test.sh

Disable golangci-lint on tip

---

profile/profile.go
profile/profile_test.go

Profile has some helper functions for manipulating the string-valued Labels associated with a Sample. These are some corresponding routines for manipulating the corresponding integer-valued Labels.

NumLabel helper functions for Profile.

---

.github/workflows/ci.yaml

The data wasn't published for several months.

Fix code coverage.

---

internal/report/report.go
internal/report/report_test.go

Add more clear err message upon disasm addr/regex

---

internal/report/report.go

Fix typo in report.go

---

internal/driver/driver.go
internal/report/report.go
internal/report/source.go

Renamed a few internal methods for clarity, and added more detail to an error message.

Handle comments from PR 831.

---

internal/driver/html/graph.css
internal/driver/html/graph.html
internal/driver/webhtml.go

Apply grab and grabbing cursor to graph UI element
