internal/graph/graph.go
internal/report/report.go
internal/symbolizer/symbolizer.go

Add diagnostic directing the user to pass the binary filename to pprof if it is not available and it is needed for local symbolization.

Add diagnostics for symbolization without mapping filenames

---

internal/binutils/addr2liner.go
internal/binutils/addr2liner_llvm.go
internal/binutils/addr2liner_nm.go
internal/symbolizer/symbolizer.go

The llvm-symbolizer tool part of llvm appears to be much faster at symbolization than addr2line, and
uses symbol table information when available.
Will still fallback to addr2line if llvm-symbolizer isn't found.

Add local symbolization using llvm-symbolizer

---

profile/legacy_profile.go

A Go redefinition error causes pprof to skip parsing profile mappings.
Inadvertently created a new variable in the inner check means the variable in the loop is not updated.

Fix error handling threadz legacy profiles

---

profile/legacy_profile.go

The legacy profilez parser handles duplicate leaf samples that are a
common artifact of stack unwinding. Apply the same technique to thread
profiles where duplicate samples also occur.

Apply leaf cleanup to threadz samples

---

profile/legacy_profile.go
profile/testdata/cppbench.contention.string
profile/testdata/cppbench.growth.string
profile/testdata/cppbench.heap.string
profile/testdata/go.godoc.thread.string
profile/testdata/gobench.heap.string

Legacy profiles that are not based on interrupt-based sampling
only include addresses that are call stack return addresses. For
them, all callstack addresses should be adjusted by -1 to land
on top of the call instruction and permit accurate symbolization.

Apply -1 adjustment to leaf frames for some legacy profiles

---

internal/driver/driver.go

The peek command allows looking at details of a function, and it
avoids any trimming to provide full details. However, when using
tagfocus it is useful to still limit to the filtered samples.
With this change peek will honor tagfocus, but it will avoid any
other trimming.

Have peek command honor "tagfocus"

---

internal/driver/driver.go

Callgrind reports are generated with line granularity since kcachegrind
can take advantage of the information. However, kcachegrind reports were
not being generated with that granularity, creating an unnecessary difference.

Generate kcachegrind reports under line granularity

---

internal/driver/commands.go
internal/driver/driver.go
internal/driver/interactive.go
internal/report/report.go
internal/report/source.go

Currently pprof will look for source files only on the current directory
and its parents. This makes it hard to examine sources on jobs where
there are multiple source trees (eg from different libraries).
Add a variable to provide a search path for source files. It will default
to the cwd, so there will be no change in behavior by default.

Add source_path option to point pprof to source files

---

internal/driver/commands.go

This enables pprof extensions to update the default for a variable
before the command line is processed.

Add mechanism for extensions to set variable defaults

---

internal/report/source.go

Reports want to use trimmed paths, not the location in the current
filesystem which may be very verbose.

Split source filepath cleanup from file opening

---

internal/graph/graph.go
internal/report/source.go

Weblist provides source and assembly combined in a web document.
It needs access to the binary to print the assembly, but currently
refuses to generate the source if the binary can't be find.
Fall back to just generating the source if the binary isn't found.
Also add an extra check on the ordering of nodes so that functions are sorted by line
number in the source report.

Allow weblist to work even if assembly is not available

---

internal/binutils/binutils.go
internal/driver/fetch.go

This will enable symbolization support for Go on Mac OS
It re-enables symbolization using debug/pprof/symbol on
Go profiles in the legacy format, and implements basic
mach-O support on the binutils package.
This should help address #12
I've only tested it with Go binaries

Add symbolization support for Mach-O

---

profile/encode.go
profile/proto.go

Preallocate arrays to avoid repeated growth during profile encode/decode

Speed up profile encode/decode

---

profile/encode.go

The proto decoder associates creates pointers to reference each
location/function/mapping based on their id. These ids can be
arbitrary uint64s, but often they are generated in sequence from
1 to N.
The overhead of keeping these indices in a hash is about a 20% of
the cost of decoding a profile. Speed it up by using an array to
track values from 1 to N, and a hash for values outside that range.

Speed up proto postprocessing phase in proto decoder

---

internal/graph/graph.go
internal/report/report.go

This will allow merging nodes for multiple instantiations of
C++ templates. A graph option is introduced to preserve older
behavior.
To implement this the full Option struct is plumbed through to the nodeInfo
function, which creates the graph Node from the profile Location. Previously
some members of that struct were passed separately.

Ignore system name when merging nodes

---

internal/driver/driver.go
internal/driver/driver_test.go
internal/driver/interactive_test.go
internal/driver/testdata/pprof.cpu.callgrind
internal/driver/testdata/pprof.heap.callgrind
internal/graph/graph.go
internal/report/report.go
internal/report/source.go

When generating callgrind format output, produce cost lines at
instruction granularity. This allows visualizers supporting the
callgrind format to display instruction-level profiling information.
We also need to provide the object file (ob=) in order for tools to find
the object file to disassemble when displaying assembly.
We opportunistically group cost lines corressponding to the same
function together, reducing the number of superfluous description lines.
Subposition compression (relative position numbering) is also used to
reduce the output size.

Instruction-level granularity in callgrind output

---

internal/elfexec/elfexec.go

This enables symbolization of some ChromeOS binaries.

Handle ET_DYN binaries with nonzero offset

---

internal/driver/commands.go
internal/driver/interactive.go

Instead of showing all active options on the command prompt, add an "options" command that
shows the currently active options.
Before:
Type: cpu
Sample types: [samples cpu]
Entering interactive mode (type "help" for commands)
Options:
edgefraction              : 0.001
flat                      : true
functions                 : true
nodefraction              : 0.005
PPROF>top 3
Showing nodes accounting for 40.08mins, 17.35% of 230.99mins total
Dropped 11940 nodes (cum <= 1.15mins)
Showing top 3 nodes out of 263
flat  flat%   sum%        cum   cum%
25.96mins 11.24% 11.24%  25.96mins 11.24%  bar
7.47mins  3.24% 14.47%   7.52mins  3.26%  foo
6.65mins  2.88% 17.35%   6.65mins  2.88%  tee
Options:
edgefraction              : 0.001
flat                      : true
functions                 : …

Add "options" command

---

internal/driver/driver.go
internal/graph/dotgraph.go
internal/graph/dotgraph_test.go
internal/graph/graph.go
internal/report/report.go

When -mean is selected, currently pprof divides the sample value
by value[0], which is expected to be the number of samples. This
is intended to produce mean value per sample. These means cannot
be added. Instead, we should add the value and the number of samples
independently and perform the division at the end.
To do this we will create a separate function to get the number of samples,
and accumulate it independently from the sample value (weigth) and apply
the division after the accumulation is completed.

Fix mean computation during graph creation

---

internal/elfexec/elfexec.go
internal/elfexec/elfexec_test.go

The kernel mapping record has the offset of 0xc000000000000000 on
PowerPC64 along with the same value for the mapping start.  Both values
come from arch/powerpc/Kconfig.  This case is not handled by any of the
conditions in the current getBase() code, so update the existing code
handling the kernel case to handle the PowerPC64 case.

Handle PowerPC64 kernel mapping in getBase().

---

internal/driver/fetch.go
internal/driver/fetch_test.go
internal/symbolizer/symbolizer.go

When the source is remote and a mapping doesn't have either build ID or
file field set, the file field is set to the source URL so that the
proper source from the source mapping is used during symbolz processing.
Before this change, the file field would continue to point to the URL
producing the URL in pprof output which confuses users.
With the change it resets the file field back to the empty string. It
also now skips the URL-like paths during local symbolization as
reading at that path is not going to succeed.
We discussed switching to generating more unique IDs. On the second
thought, I propose leaving these to be URLs as that seems unique enough
and in case this field leaks into the tool or log output seeing the URL
seems still friendlier than some arbitrarily prefixed string.

Reset mapping file to empty string if it was patched to be the source URL

---

driver/driver.go
internal/binutils/addr2liner.go
internal/binutils/binutils.go
internal/driver/driver.go
internal/driver/testdata/pprof.cpu.flat.addresses.weblist
internal/elfexec/elfexec.go
internal/graph/dotgraph.go
internal/graph/graph.go
internal/measurement/measurement.go
internal/plugin/plugin.go
internal/report/report.go
internal/report/source.go
internal/symbolz/symbolz.go
pprof.go
profile/encode.go
profile/legacy_profile.go
profile/merge.go
profile/profile.go
profile/profile_test.go
profile/prune.go

- Remove dead code, unnecessary conversions
- Consistently use a single space after period

Upstream minor changes from golang version of pprof

---

internal/driver/commands.go
internal/driver/fetch.go

Only create $HOME/pprof if a profile is stored remotely
and must be stored. Also, create non-profile temps on
os.TempDir() instead of $HOME/pprof or /tmp.

More careful handling of temporary directories

---

internal/driver/testdata/pprof.heap.flat.inuse_space.dot.focus.ignore
internal/graph/graph.go

Do not remove a residual edge between A and B if there isn't another path
going between A and B. We previously would remove it if A and B had a common
ancestor, but that caused some value duplication as A could become a leaf
but its value would still be accounted for in B.

Keep more residual edges

---

internal/driver/driver.go
profile/legacy_profile.go
profile/profile_test.go

A previous commit tried to eliminate a panic when reading an empty
profile by stopping support for profiles with no samples. That is
unnecessary and it can obstruct some testing.
The panic was caused by the legacy parser returning a nil profile and
no error when processing an empty profile. Detect that situation and
generate a proper profile instead.
Tested by running 'pprof /dev/null'

Allow profiles with no samples

---

profile/legacy_profile.go

See https://github.com/google/pprof/issues/54. Frames under
call32/call64 may be user code frames so should be shown to avoid
confusing re-attribution of allocations to the calling system frames.

Do not hide allocation frames under call32/call64.

---

profile/legacy_profile.go

This uses https://go-review.googlesource.com/#/c/33635 instead of the
previous change to fix https://github.com/google/pprof/issues/54.

Use the better fix for the issue with reflected calls in heap profiles

---

driver/driver.go
internal/binutils/disasm.go
internal/binutils/disasm_test.go
internal/driver/driver_test.go
internal/driver/testdata/pprof.cpu.flat.addresses.disasm
internal/driver/testdata/pprof.cpu.flat.addresses.weblist
internal/plugin/plugin.go
internal/report/report.go
internal/report/source.go

Disassembly reports generated by pprof -disasm will now include line number
information as generated by objdump. This will make the generated assembly more
readable.
As part of this I've introduced a new assemblyInstruction struct. Previously
the code was reusing the graph.Node to represent assembly instructions but it
seems better to have a dedicated type for this.

Add source information to disassembly reports

---

internal/driver/commands.go
internal/driver/driver_test.go
internal/driver/testdata/pprof.heap.comments
internal/driver/testdata/pprof.heap.flat.inuse_space.dot.focus
internal/driver/testdata/pprof.heap.flat.inuse_space.dot.focus.ignore
internal/driver/testdata/pprof.heap.flat.lines.dot.focus
internal/driver/testdata/pprof.heap_alloc.flat.alloc_space.dot.focus
internal/driver/testdata/pprof.heap_alloc.flat.alloc_space.dot.hide
internal/report/report.go
profile/profile.go

By default hide entries in the comment field that starts with #, and
add a "comments" command to show all comments.
Also sort the command lists and update driver tests to include comments.

Improve support for the Comments field

---

internal/report/report.go
internal/report/report_test.go

Instead of putting a pretty-printed string on the function.name,
populate the function.name, .file and location line with the
information from the node. This will help more easily extract this
information.
Also add some cachign to reuse functions and added a small test.

Populate more carefully the profile.proto in the topproto output

---

profile/legacy_profile.go
profile/legacy_profile_test.go
profile/profile_test.go

Simplify regexps and define a recommended format:
Start   End     object file name     offset(optional)   linker build id
0x40000-0x80000 /path/to/binary      (@FF00)            abc123456
Also include some additional tests and move existing tests to legacy_profile_test.go,
closer to the code in legacy_profile.go.

Improve regexp matching of mappings for legacy formats

---

profile/legacy_profile.go
profile/legacy_profile_test.go

Entry mappings of the form:
"  02e00000-02e8a000: /foo/bin (deleted)"
are currently resulting in "(deleted)" being set as the build id.
Enforce the build id to be hex, and allow unrecognized junk to
be at the end of the mapping.

Parse correctly mappings where the binary has been deleted

---

internal/symbolizer/symbolizer.go

The common mechanism to locate the main binary has several drawbacks:
- The identification of the main mapping is done through heuristics
- It can only override the main binary, no libraries
PPROF_BINARY_PATH is a more robust mechanism, but it isn't widely known.
Add a message when symbolization fails recommending its usage.

Add a message recommending the use of PPROF_BINARY_PATH

---

internal/symbolizer/symbolizer.go
profile/profile.go

The local symbolization already skips these mappings. Have the helper which can be used when alternative symbolization flows are used.

Add a helper function to check if a mapping is unsymbolizable

---

profile/profile.go

Trying to symbolize files like /dev/dri/renderD128 makes pprof hang as
it tries to read from this device file. So do not attempt the symbolization.
Skip [heap] file, too - the profile from issue #78 has a couple samples
in the heap (perhaps some generated code) and trying to locate a file
with that name can't succeed.
Fixes #78.

Do not attempt to symbolize /dev/dri/* and [heap] files.

---

internal/driver/fetch.go

The source is already included in the error, so it is redundant, eg:
pprof http://nowhere.nothere
Currently produces:
http://nowhere.nothere: http fetch http://nowhere.nothere: Get http://nowhere.nothere: dial tcp: lookup nowhere.nothere: no such host
With this commit:
http://nowhere.nothere: http fetch: Get http://nowhere.nothere: dial tcp: lookup nowhere.nothere: no such host

Remove source from fetch error message

---

profile/legacy_profile.go
profile/legacy_profile_test.go

In addition to the "goroutine" and "threadcreate" profiles,
Go code can generate custom profiles using the runtime/pprof package.
The user must name these profiles, and the docs recommend using the
convention "import/path" to avoid namespace conflicts.  This CL
updates the pprof tool to be able to parse legacy profiles whose types
contain slashes and other non-space characters.
This is the upstream fix for https://github.com/golang/go/issues/13195.
This change will need to be mirrored to
github.com/golang/go/src/cmd/pprof/internal/profile/legacy_profile.go

profile.parseGoCount: accept non-space characters in profile type.

---

internal/driver/fetch.go

Allow pulling profiles from a device that is only accessible through a proxy. The proxy is to be specified with the usual HTTP_PROXY environment setting.

Honor environment proxy settings

---

internal/driver/fetch.go
internal/symbolizer/symbolizer.go

Upstreaming change from golang/go@39366326.
HTTP body will be read and displayed when both conditions are true:
* Response includes non-empty header "X-Go-Pprof".
* Content-Type is text/plain.
Would it be acceptable to move the fetch functions into a separate `fetch` package as it is in golang/go? This PR currently duplicates the `statusCodeError()` function in packages `internal/driver` and `internal/symbolizer`. Importing from `internal/driver` into `internal/symbolizer` causes an import cycle. `internal/symbolizer` to `internal/driver` doesn't cause a cycle but seems like a less than ideal structure.

Display HTTP errors from server

---

internal/driver/commands.go
internal/driver/driver.go
internal/driver/interactive_test.go
third_party/svg/svg.go

For certain formats (eog, evince, gv, web, weblist), the visualizer
would be invoked regardless of whether the user specified a specific
output file to write to. In order to ensure that output is properly
written, the invokeVisualizer function has a check for whether the
output is os.Stdout and alters behavior based on that. This is the
wrong abstraction layer to do that work.
At the core of the problem is that PostProcess is used to both
do data post-processing that is inherent to the format, and also
to invoke some visualization for the data (to Stdout or browser).
We split these two steps apart and make it obvious which is which
by adding a visualizer field to Command.
This seperation of concerns allows us to simplify the code.

Clean-up handling of output flag

---

internal/symbolizer/symbolizer.go

Fixes executables named on the command line on Windows.
Fixes the build failure on https://go-review.googlesource.com/#/c/36798 patch set 6.

pprof/internal/symbolizer: do not recognize C:\foo\bar.exe as a URL

---

internal/driver/driver_test.go
internal/driver/fetch_test.go
internal/proftest/proftest.go
internal/report/report_test.go

Skip TestSymbolizationPath (seems too Unix-specific).
Fix others with golden output to adjust for Windows file name syntax.

pprof: fix tests on Windows

---

doc/pprof.md
internal/driver/cli.go
internal/driver/fetch.go

Not all OSes have $HOME variable.
Use appropriate variables per OS.
Fixes https://github.com/golang/go/issues/18864

internal/driver: avoid using $HOME directly

---

driver/driver.go
internal/binutils/addr2liner.go
internal/binutils/addr2liner_llvm.go
internal/binutils/binutils_test.go
internal/binutils/disasm.go
internal/binutils/disasm_test.go
internal/driver/fetch_test.go
internal/driver/options.go
internal/report/report_test.go
internal/symbolizer/symbolizer_test.go

Mainly use imported structs by field and update a mismatch printf
string on a test error message.
As requested at https://github.com/golang/go/issues/19322

Fix issues reported by govet

---

internal/driver/fetch_test.go

In changeset f90721db3d, fetch.go was changed to handle
the correct home directory environment variable on Plan 9
and Windows, but the tests were still using the $HOME
environment variable.
We change the tests to use the homeEnv function instead
of the $HOME environment variable.
Fixes #100.

internal/driver: use homeEnv function in tests

---

internal/driver/fetch_test.go

Surprisingly these don't show up with go vet, but still cause issues
for the Go distribution.
Related to https://github.com/golang/go/issues/19322

More govet fixes

---

profile/profile.go

Do so by relaxing the matching to treat all mappings for file names starting with a '[' as not symbolizable.

Make [vsyscall] recognized as a not symbolizable mapping.

---

internal/driver/driver_test.go
internal/driver/testdata/pprof.cpu.call_tree.callgrind
internal/driver/testdata/pprof.cpu.flat.functions.call_tree.dot
internal/driver/testdata/pprof.unknown.flat.functions.call_tree.text
internal/report/report.go

There is a check to only honor the call_tree option when generating non-visual
reports, but it wasn't being checked in all appropriate places, causing a
mismatch that triggered a panic.
This fixes #103

Do not honor call_tree option when generating non-visual reports.

---

internal/driver/driver_test.go
internal/symbolizer/symbolizer.go

Added a test, verified the test failed before the fix.
This fixes #94.

Recognize https+insecure scheme for symbolization POSTs.

---

internal/driver/driver_test.go
internal/symbolizer/symbolizer.go

Reverts google/pprof#111 as the test is reported to fail with Go 1.8.

Revert "Recognize https+insecure scheme for symbolization POSTs."

---

.travis.yml
README.md

Go 1.6 currently fails the tests with build error
`profile/legacy_profile_test.go:309: t.Run undefined (type *testing.T has no field or method Run)`
Alternatively, we can fix it but I am not sure there is a strong reason
to support Go 1.6 or older.
Also add build status badge in the README.md file.

Clarify that Go 1.7 or newer is required.

---

internal/driver/driver_test.go
internal/symbolizer/symbolizer.go

This reverts the revert of #111 relaxing the test to make it pass as the
issue reported in #111 is caused by unrelated #120.
Added a test, verified the test failed before the fix.
This fixes #94.

Recognize (again) https+insecure scheme for symbolization POSTs.

---

internal/driver/driver_test.go
internal/driver/fetch.go
internal/driver/fetch_test.go

Use a more regular mechanism to name sources during driver tests and
recognize the naming during fetching to avoid saving the test profiles
into $HOME/pprof.
Also move the https+insecure testing into fetch_test, to focus it on
fetching the profile.
This fixes #107

Special case fetching for driver tests

---

internal/graph/dotgraph.go
internal/graph/dotgraph_test.go
internal/graph/graph.go

There is an issue where decreasing nodefraction (which should produce
more nodes) ended up reducing the number of displayed nodes.  This is
because we have an upper limit on number of nodes to display and the
number of node-lets counts against that limit.  This can cause a problem
if a node with large number of node-lets shows up near the front of
the list of nodes (e.g., std::allocator_traits::allocate in a heapz
profile had 102 node-lets, which caused all subsequent nodes to be
dropped).
Fixed by limiting the count of charged node-lets per node to
maxNodelets (4), which is the maximum number of node-lets we
display per node.

Fix unstable nodefraction handling

---

profile/prune.go
profile/prune_test.go

When pruning unsimplified names, don't trim "(anonymous namespace)".

---

internal/driver/cli.go
internal/driver/driver.go
internal/driver/webui.go
internal/driver/webui_test.go

If non-local hosts are provided, localhost-only authorization is skipped.

Allow -http to accept host:port

---

internal/driver/fetch.go
internal/proftest/proftest.go

Without the check, pprof may try using a path like "/pprof" when no
home environment variable is defined.
Fixes #148.

Avoid using $HOME when it's empty.

---

.travis.yml
internal/driver/fetch_test.go

TestHttpsInsecure test runs a profiling session and checks that the
results contain expected function name. On OSX prior to 10.11 El Capitan
the SIGPROF signal is delivered to the process rather than to the thread
which skews the results enough for the test to fail.
Relax the check when running on OSX and other operating systems known to
have issues with the profiling signal (the list is taken from
src/runtime/pprof/pprof_test.go in Go source).
Also add the multiple variants of OSX to the continuous testing.
Fixes #146 and fixes #156.

Make TestHttpsInsecure test reliably passing on Darwin.

---

internal/driver/webui_test.go

These tests passed in Appveyor and in Travis, but failed when using blaze, preventing internal release.
The test with hostport  equaling "127.0.0.1" likely fails because "127.0.0.1" is interpreted as ipv4, so will fail on systems where only ipv6 is supported.
The test with hostport equaling "localhost:12344" likely fails with blaze because the allowable port range is controlled. This test will likely also fail if the port is bound to other processes when the test runs.

Removed tests which failed on some systems

---

internal/driver/webui.go
internal/driver/webui_test.go

When net.SplitHostPort is called, it will return the string "::1",
but the code was only checking for "[::1]".
Fixes #174.

Fix unexpected webui permission error on an IPv6 configured machine

---

README.md
internal/driver/cli.go

Docs are stale, -http flag now supports host:port.

Update docs to reflect the changes for the -http flag

---

profile/filter.go
profile/profile_test.go

FilterSamplesByName should return true for hnm only when
"at least one sample" matched the show regexp.
Before this commit it always returned true
if the show regexp is not nil and p.Location is not empty.

profile: FilterSamplesByName returns the correct hnm

---

internal/driver/webui.go

When wrap is nil but isLocal is false, we segfault when we attempt to wrap mux handlers.

Fix segfault in webui when there is no authorization wrapper

---

internal/driver/cli.go

Add legacy options to command-line help

---

internal/driver/webhtml.go
internal/driver/webui.go
internal/driver/webui_test.go
internal/report/report.go

Details:
* New /top URL that generates a tabular display.
* Split-up template into reusable templates (shared by / and /top).
* Sanitized web page header to contain a single menubar.
* Fixed bug in javascript node name handling (names were regexp-quoted, but were being treated as plain strings).
Attached zip file contains sample output.
[sample.zip](https://github.com/google/pprof/files/1236737/sample.zip)

Extend web UI to contain a tabular "top" display

---

internal/driver/driver_test.go
internal/symbolizer/symbolizer.go
internal/symbolizer/symbolizer_test.go
internal/symbolz/symbolz.go
internal/symbolz/symbolz_test.go

The code parsing symbolize options was treating the empty option as
"force", effectively making -symbolize=force the default. This would
unnecessarily symbolize profiles that were already symbolized.

Stop treating -symbolize=force as the default

---

internal/driver/webhtml.go
internal/driver/webui.go
internal/driver/webui_test.go
internal/report/report.go
internal/report/source.go
internal/report/source_html.go

Details:
* Made it easier to reuse css, javascript, etc. across views.
* Added two new templates: sourcelisting, plaintext.
* Use new templates for showing source code, disassembly, peek.
* Merged Functions menu into View menu.
* View change menu entries are now always enabled.
* Removed now unused "newWindow" argument to navigate.
* Removed redundancy in web handlers.
* Renamed /weblist URL to /source.
* Assembly and source code listings are now limited to 500 functions
sorted by decreasing flat value (to prevent huge delays when
selecting asm/source view across the entire profile).

Use common header for remaining web views (source code, disassembly, peek)

---

internal/driver/webui.go
internal/driver/webui_test.go
internal/plugin/plugin.go

HTTPServer allows somebody embedding pprof to control how the
hosting HTTP server is constructed which makes pprof work in
more environments.

Replaced http wrapper field in plugin Options with HTTPServer.

---

internal/driver/driver.go
internal/driver/driver_test.go
profile/profile.go
profile/profile_test.go

Now, warnings will only be printed if multiple units are associated with one key, but not if units are inferred based on the keys, units are inferred, or some values are missing units.
Fixes #239

Fix unit warnings

---

internal/driver/webhtml.go

Previously, users had to be careful to not move the mouse
outside the menu (otherwise it would disappear unintentionally).
Also fixed a minor bug where we were not overwriting URL
parameters correctly when no selection was made.

Show menu on click, not hover.

---

internal/symbolizer/symbolizer.go

Errors due to unwanted status codes in POST responses give no URL context. This adds it to match the style used for connection issues. This is useful for example when symbol look fails and generates a 404. Previously there was no mention of why a 404 error occurred, and the action that triggered it.

Improve POST URL status error

---

internal/driver/webui_test.go

Should fix #251.
In #229, TestWebInterface was modified the server, so it now runs in a separate thread.
I think that this changes how tests interact with the server, so it runs into limitations similar to those which caused #196 (specifically that tcp isn't available on nacl).

Skip TestWebInterface on nacl

---

internal/driver/fetch_test.go

These two changes fix TestHttpsInsecure on Plan 9.
Fixes #253.

Fix TestHttpsInsecure on Plan 9

---

internal/driver/fetch_test.go

Also, replace a PrintErr with Print to avoid a warning message
being registered as an error.
This will in turn fix golang.org/issues/22612 for the Go iOS
builders.

internal/driver: skip TestHttpsInsecure test on iOS

---

CONTRIBUTORS
internal/driver/testdata/pprof.cpu.flat.addresses.weblist
internal/driver/webhtml.go
internal/report/source.go

Update the web user interface aesthetically.
The Refine menu is greyed-out for pages besides the Graph.
The description box now opens upon clicking the filename in the top-right.

Update the web user interface aesthetically

---

internal/driver/flamegraph.go

Further testing revealed an issue with the flame graph search function. Since a node list was not being exported anymore after the `call_tree` change, the `selectMatching` function was throwing an exception because the the list was `null`. This is a simple fix, following the same approach as the _dot_ view and exporting the node name list again. The other option would be to move a few functions out of the `{{define "script"}}` template, load them separately in the _dot_ view, and not call the `viewer` function in the flame graph view.

fix: viewer function receiving null node list

---

appveyor.yml

Graphviz has failed to install on appveyor tests, so appveyor does not pass.
This change makes it so graphviz can again be successfully installed on appveyor.

Fix graphviz installation on appveyor tests

---

.travis.yml

Fixes #255 
Sometimes graphviz fails to install on xcode6.4. To address this, this change will stop graphviz from being installed on xcode6.4. Tests depending on graphviz will be skipped on xcode6.4.

Skip graphviz install on xcode6.4

---

internal/symbolz/symbolz.go
internal/symbolz/symbolz_test.go

Here are the changes I have made to restore compatibility with the old pprof. I have left `strings.Contains(url.Path, "/debug/pprof/")` in the condition, together with the two `HasSuffix()` tests I have added. Leaving it seemed like the safe thing to do.

Change URL matching code to restore compatibility with old pprof (#276)

---

internal/driver/commands.go
internal/driver/svg.go
third_party/svgpan/LICENSE
third_party/svgpan/svgpan.go

The third_party svg directory has been a mix of pprof-specific code and
svgpan itself. This change moves the pprof-specific code out and adds a
license file. It also updates svgpan to 1.2.2 from
https://github.com/aleofreddi/svgpan while we are here. It also renames
the directory to svgpan to have all directories under third_party be
named precisely over the third party package they hold.

Update svgpan, add license, separate pprof-specific code.

---

internal/driver/webhtml.go

Pull request #263 disabled the refine menu for any views other than
Graph, but that's not expected - it's perfectly fine to use it for Flame
and Top, so just keep it enabled.
Fixes #285.

Keep refine menu enabled for views other than graph.

---

internal/driver/fetch_test.go

On an instance of the Android emulator running x86_64, $HOME points
to / which is not writable. Add Android to the list of GOOS where
the temp dir error is skipped.
Fixes the android/amd64 and android/386 builders on build.golang.org.

internal/driver: ignore temp dir error on Android

---

internal/symbolizer/symbolizer.go
profile/encode.go
profile/merge.go
profile/profile.go
profile/profile_test.go
profile/proto_test.go
proto/profile.proto

Modified pprof to keep is_folded bit during encoding and decoding, factor in is_folded bit during merges, and print is_folded bit when converting profile to string.

Support parsing of is_folded bit

---

internal/driver/driver_test.go
internal/driver/webui_test.go

The current version of go vet does not flag these as noted in
golang/go#23539. A fix is in the works, and will likely be included in
Go 1.11. Make the updated vet tool happy, so that the vendored copy of
pprof in the Go tree can be updated and make the vet trybot happy.
Fixes #297.

internal/driver: fix new unkeyed composite lit vet warnings

---

internal/binutils/binutils.go
internal/binutils/binutils_test.go
internal/elfexec/elfexec.go

When pprof symbolizes kernel addresses in vmlinux binary for a profile
converted using https://github.com/google/perf_data_converter, the
addresses need to be adjusted if kernel ASLR is in effect. So far the
call to GetBase did not pass text segment info to GetBase which
shortcircuited the code to merely return zero adjustment. This change
fixes the call to GetBase to address that.
The added test case is an approximation of what happens with vmlinux,
but it should be pretty close. Including a vmlinux file into the test data
does not appear practical due to the binary size. I verified that the test
failed before the fix and passes after.
Note that the fixed issue is specific to the kernel ASLR as user-mode
ASRL-enabled binaries (i.e. built with -pie / -fpie) have ET_DYN type
which takes a …

Pass text segment info to GetBase to handle Linux kernel ASLR case.

---

internal/driver/fetch_test.go

Debian builds packages with HOME set to a bogus value and this causes tests to
fail when packaging Go 1.10...

Set HOME to a temporary directory in TestHttpsInsecure

---

profile/encode.go
profile/profile.go
profile/profile_test.go

This change detects concatenated profiles by checking if time_nanos appears more than once in the profile being parsed. 
Fixes #273

Detect concatenated profile and give clearer error message

---

internal/driver/fetch_test.go

The test overrides $HOME now so the checks are not needed now.

Remove runtime.GOOS checks that are redundant as of #305.

---

internal/driver/webui.go
internal/driver/webui_test.go

This fixes #307.
When the port is not specified with the `-http` option, a random port is selected using `net.Listen()`.

Use random port when no port specified with -http

---

internal/driver/webui_test.go

This fixes test failure described in #300.
The response from http.Get() was not previously read, which caused http.Get() to hang forever.

Read response from http.Get() in TestWebInterface, so http.Get() does not hang

---

.travis.yml

PR #270 want meant to stop installing graphviz on xcode6.4 to fix #255.
However, #270 also stopped graphviz from being installed on  xcode7.3 and xcode8.3 (issue #317).
This PR modifies .travis.yml so graphviz is installed on   xcode7.3 and xcode8.3.
Completed build: https://travis-ci.org/nolanmar511/pprof/builds/339568567
I confirmed that TestWebInterface ran on all linux builds, all xcode7.3 and xcode8.3 builds, but not on any xcode6.4 builds.

Install graphviz on xcode7.3 and xcode8.3 travis builds 

---

internal/driver/driver.go

#329 (The function internal/driver.generateReport does not use o.Writer to write output)

Use o.Writer if not nil to write output

---

internal/driver/fetch.go

Fixes #277
As perf_to_profile uses flags to parse its arguments, modify the call to perf_to_profile to use flags. Also pass the '-f' flag to overwrite the existing output profile file.
Redirect perf_to_profile's stdout/stderr to pprof's stdout/stderr.
Tested by executing pprof with a perf.data:
Eg:
perf record -e cycles -o perf.data -- sleep 1
./pprof perf.data

Update perf_to_profile cli arguments to use flags. (#277)

---

internal/driver/interactive.go

In the interactive mode, inform users of different sample types
if the profile includes zero samples for selected sample type
by default (or through user-provided sample_index flag value).
The example output may look like
$ pprof mem.prof
Type: inuse_space
Time: Mar 20, 2018 at 11:36am (EDT)
No samples were found with the default sample value type.
Try "sample_index" command to analyze different sample values.
Entering interactive mode (type "help" for commands, "o" for options)
(pprof)
Update golang/go#24443
I believe ultimately the profile producer should annotate the profile 
with the appropriate default index. I hope this helps users to learn about the 
next step when encountering zero sample issues reported in the bug 
until then.

internal/driver: suggest sample_index in case empty default samples

---

internal/driver/fetch.go

pprof can not find a dependency in the format created by perf.
pprof checks:
`path/m.BuildID/Base(m.File)`
`path/Base(m.File)`
`path/m.File`
But perf build path in format:
`path/m.File/m.BuildID`
For example:
`RELPATH/usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0/fd6376149047833953b0269e84de181ca45dbe90`

internal/driver: allow local symbolization with perf path format

---

driver/driver.go
internal/driver/driver.go
internal/driver/webui.go
internal/driver/webui_test.go

This allows embedding the pprof ui into an existing application. See
https://github.com/cockroachdb/cockroach/pull/24145 for an example.
The second change replaces e82ee9a. It may look cosmetic, but note that
`plugin.UI` can be passed in from the outside. This is important for embedding
pprof into an application for easy access to the web ui: with this change, such
an application can pass a non-Terminal `profile.UI` and avoids the browser
code which doesn't make sense in that context.

Allow passing in a custom HTTPServer

---

driver/driver.go
internal/driver/options.go
internal/driver/webui.go
internal/driver/webui_test.go
internal/plugin/plugin.go
internal/proftest/proftest.go

This fixes a bug introduced in #341 which caused the browser
opening code to be disabled for the standard `pprof -http`
invocation.
Introduce a proper getter on the UI which determines whether
the browser ought to be opened.

Introduce (UI).WantBrowser

---

internal/driver/flamegraph.go
internal/driver/webhtml.go
internal/driver/webui.go

Previously, the web UI was hard-coded to be served at `/` but
applications which are *embedding* the ui are unlikely to host it there.
This change makes the links between the various ui pages relative,
addressing this problem.
To make sure this doesn't rot, the internal http server now serves the
ui at /ui/ (redirecting there from the root).
I think we can all agree that the ui code and JavaScript is kind of a
haphazard affair. I performed a great deal of clicking around to make
sure the semantics didn't change and interestingly spent some time
trying to fix semantics I later realized weren't actually there: I
thought that when navigating to another page from a focused search (say
`flamegraph?f=x`) the focus would be carried over. This doesn't seem to
be the case, however.
The point …

Allow serving web ui at arbitrary root

---

.travis.yml
internal/binutils/binutils.go
internal/binutils/binutils_test.go

Detect when binutils are not installed on OSX and skip the test.

---

internal/driver/cli.go

The code was updated in #335 but the doc wasn't updated. Also the doc
didn't include $path which is searched as well, see locateBinaries in
internal/driver/fetch.go.

Update -help to list correct paths searched within PPROF_BINARY_PATH.

---

internal/driver/fetch.go

Starting around yesterday, CI fails with Go master version - https://travis-ci.org/google/pprof/jobs/363261750. Apparently there was a fix in Go that change how this specific place in code is formatted. The new version does make sense, but failing CI is bad, so hack the code fragment to make it formatted the same with all Go versions. Yep, it's a hack.

Hack the code so that both existing Go versions and current Go master format it the same

---

appveyor.yml
pprof.go

Implement basic command-line editing, using github.com/chzyer/readline. This will not affect the golang
distribution as it uses its own pprof driver, with its own driver.
Fixes #57.
Only tested on Linux.
TODO: Implement auto-completion and persistent history.

Add command-line editing support for interactive pprof

---

internal/driver/commands.go
internal/driver/driver.go
internal/report/report.go

This is a step in implementing changes described in #323

remove -positive_percentages flag

---

internal/driver/commands.go
internal/driver/driver.go
internal/report/report.go
internal/report/report_test.go
internal/report/source.go
internal/report/source_test.go

When pprof is asked to show annotated source for a profile collected on
another machine for a Go program, the profile contains absolute paths
which may not exist on the local machine. In that case pprof currently
fails to locate the source with no option to help it. The new option
adds a way to specify one or several source path prefixes that should be
trimmed from the source paths in the profile before applying the search
using search path option.
For example, taking the example from the issue where the source file
path in the profile is
/home/teamcitycpp/agent09/work/56cbaf90675b10ff/_gopath/src/badoo/lakafka/main.go
and the local path is /home/marko/lakafka/main.go. The user may
specify
`-trim-path=/home/teamcitycpp/agent09/work/56cbaf90675b10ff/_gopath/src/badoo`
to make pprof find …

Add "trim path" option which can be used to relocate sources.

---

doc/README.md
internal/driver/cli.go
internal/driver/driver_test.go
internal/driver/fetch.go
internal/driver/fetch_test.go
internal/report/report.go
internal/report/report_test.go
profile/profile.go
profile/profile_test.go

Part of fixing #323.
Changes made to design:
* Using key "base" and value "1" to mark profiles in the base profile, rather than key "pprof::base" (or "pprof::diff") and value "true", because we don't want to use long values (the are lots of samples, so adding lots of tags might increase memory usage too much).
* Using `-diff_base`, rather than `-diff` as the flag name. It should be clearer.

add -diff flag for better profile comparision

---

profile/legacy_profile.go
profile/legacy_profile_test.go

This CL fixes a long-lasting bug that prevented pprof from recognizing
Legacy heap profile produced by Go. Go reports four types of samples
at once so the profile includes alloc_objects, alloc_space,
inuse_objects, and inuse_space. The bug caused pprof to misclassify Go
heap profile data and prevent selection of correct filtering/pruning
patterns in analysis.
Update golang/go#25096
Tested with the profile samples included in golang.org/issues/25096
(pprof hides the runtime functions with this change)

profile: fix legacy format Go heap profile parsing

---

internal/graph/graph.go
internal/graph/graph_test.go

In some cases pprof isn't saving the module name in graph nodes, so
reports end up with nodes of the form '<unknown>'.
The module name is often stripped to allow symbolized frames from
different versions of a binary to be merge.
Force saving the objfile name if the name is unknown so we can print
some information for unsymbolized frames.

Force saving the module name for unsymbolized frames

---

internal/driver/commands.go

Fixes first issue mentioned in #389
Order of commands matches go's [cmd/internal/browser Commands()](https://github.com/golang/go/blob/46076c37578fba9b49059584ef896099c9240fb2/src/cmd/internal/browser/browser.go#L18) function, except that "sensible-browser" is added when no on windows or darwin, and "xdg-open" is added even when "DISPLAY" env variable is not set.

update order of available browsers

---

internal/symbolz/symbolz.go
internal/symbolz/symbolz_test.go

Fixes #280. 64-bit addresses with the high bit set should be adjustable
as long as the offset does not overflow the result. This change
supersedes #396 avoiding `math/big` dependency.

Handle 64-bit negative addresses when adjusting them.

---

internal/driver/driver.go
internal/driver/driver_test.go

We've had some discussion, and concluded that user-specified filters should be applied to the -proto output format.
This change makes it so that filters are applied to the -proto output.

apply filters to -proto output format

---

test.sh

See https://travis-ci.org/google/pprof/jobs/412151752 for example failure.

Fix staticcheck warning SA6004 that was recently added in the tool

---

internal/driver/webui.go

The option is exposed in the web UI's query string under a
new `?si=<sample_index>` parameter. This is particularly
useful for heap profiles, where switching between the four
indices (alloc_objects, alloc_space, inuse_objects, and inuse_space)
is a common task.
We could add a menu to the UI to make discovery of these
options easier, but for now this seems sufficient.

Expose sample_index argument through web ui

---

internal/driver/webhtml.go
internal/driver/webui.go

This is a follow-up change to #412 which adds a selector to the web
ui for selecting the sample index of a profile to view. The selector
is hidden for profiles with only a single sample type.

Add sample index selector to web ui

---

internal/driver/commands.go

The browser() function prioritize opening commands which definitely open browsers, since this function is used as a command to open the svg graphs, and these graphs have embedded javascript which makes them easier to navigate.
Fixes #402

Change order of commands returned by browser()

---

doc/README.md
internal/driver/commands.go
internal/driver/driver.go
internal/driver/driver_test.go
internal/driver/interactive_test.go
internal/driver/testdata/pprof.cpu.flat.addresses.noinlines.text
internal/driver/testdata/pprof.cpu.flat.filefunctions.noinlines.text
internal/driver/testdata/pprof.cpu.flat.functions.noinlines.text

This change consists of two relatively independent parts, but they are
both about handling the granularity, so bundling them together.
First, in #415 there is a discussion that having a granularity mode by
source lines but with inlines hidden would be useful. The agreement is
also that adding `-linenoinlines` granularity would make the granularity
flags too messy (and they are already somewhat messy with `-addresses`
and `-addressnoinlines`. So, it was proposed to make `-noinlines` a
separate flag, which is what this change does. Note that the flag is now
pulled out of the granularity group so it's a bit of backward
incompatible change but I think it is acceptable. For the example in
issue #415 the user would now be able to specify `-list foo -noinlines`
to produce annotated source where …

Make '-noinlines' a separate flag, introduce '-filefunctions' granularity

---

.travis.yml
internal/elfexec/elfexec.go
internal/elfexec/elfexec_test.go

I was looking at a report where pprof wouldn't symbolize the data
collected for a Chrome binary using Linux perf (b/112303003). The mmap
information is:
start: 000000000272e000, limit: 0000000006b09000, offset: 000000000252f000
The ELF file header:
elf.FileHeader{Class:elf.ELFCLASS64, Data:elf.ELFDATA2LSB, Version:elf.EV_CURRENT, OSABI:elf.ELFOSABI_NONE, ABIVersion:0x0, ByteOrder:binary.LittleEndian, Type:elf.ET_EXEC, Machine:elf.EM_X86_64, Entry:0x272e000}
The code segment:
elf.ProgHeader{Type:elf.PT_LOAD, Flags:elf.PF_X+elf.PF_R, Off:0x252f000,
Vaddr:0x272e000, Paddr:0x272e000, Filesz:0x43da610, Memsz:0x43da610,
Align:0x1000}
The dynamic loader here mapped 0x6b09000-0x272e000 = 0x43db000 bytes
starting 0x252f000 file offset into 0x272e000 virtual address, exactly
as instructed by the …

Fix ELF base calculation for exec mapping with offset != 0

---

.travis.yml
README.md

Also update the text around supported Go versions - refer to the
Go's policy on that which is two latest major releases.

Fix the CI build failing on master from "go tool vet" command.

---

internal/driver/cli.go
internal/driver/webui.go

Master branch of PPROF has a bug introduced 8 months ago by #348 which breaks invocations like:
`pprof -http localhost:8080 -alloc_space <FILE>`
If you run that command, it will display `inuse_space` instead of `alloc_space`. The reason is that the decision to display `alloc_space` is propagated as a query arg, and the `http.RedirectHandler` that the existing code is using doesn't propagate them.
I verified the bug exists (and is fixed in this P.R) by running the same command described above.

[Bug Fix] Propagate query args during URL redirect to preserve heap allocation type

---

internal/driver/webhtml.go

This adds `flamegraph` to the list of dynamic search links so that query parameters (esp. regex filters) are retained when navigating to/from the flamegraph view. This seems to just be an oversight since flamegraph was added later as a visualization option.
I have tested it manually by applying filters in the "Graph" view and then navigating to "Flame Graph". You can also see that, after this change, the `href` for the flamegraph link is dynamically updated with any query parameters like the other links:
Previously, the `href` would always be fixed with `./flamegraph` (from the template), so navigating to the flamegraph would reset all filters and other query parameters.
Fixes #431

Add flamegraph to list of dynamic search links

---

test.sh

`staticcheck`'s `-ignore` flag [has been removed](http://staticcheck.io/changes/2019.1) in favor of [Linter directives](http://staticcheck.io/docs/#ignoring-problems), and the `unused` tool was merged into `staticcheck`, breaking the Travis build. These lint ignores may not be necessary anymore anyway due to improvements in the static checker.

Fix Travis build call to staticcheck

---

internal/driver/webhtml.go

`updateUrl` was refactored in away in #414, leading to `Uncaught ReferenceError: updateUrl is not defined` (and the keypress no longer works).
For the `sourcelisting` page, [`nodes===null`](https://github.com/google/pprof/blob/master/internal/driver/webhtml.go#L1019), leading to: `Uncaught TypeError: Cannot read property 'length' of null`.
These fixes were validated through manual testing. I believe given the scope of the changes they are unlikely to cause distant regressions.
Fixes #463.

Fix keypress focus: updateUrl is not defined

---

internal/driver/webhtml.go

I have noticed, that in the web ui, the icon of magnifier glass of the search input isn't rendered. Of all browsers that I've checked Safari is the only one that renders the icon, while in Firefox and Chrome the icon is missing:
This PR fixes, what I believe was a typo, by escaping the hex value of icon's fill colour.
**Update** After the fix:

webhtml: fix search input svg icon

---

internal/driver/webhtml.go

This sorts flamegraph elements lexicographically such that two similar profiles can be compared side-by-side to eyeball differences in flamegraph profile shapes and sizes.
Flamegraph elements prior to #367 were sorted, but since then, it has been difficult to eyeball 2 similar profiles side-by-side, as the elements appear in a somewhat random order.

webhtml: reenable sort option for flamegraphs

---

internal/graph/graph.go
internal/graph/graph_test.go

For C++ functions, the template parameters should be kept as part of shortened names.
Generally, template parameters are stripped from the C++ names but when `-symbolize=demangle=templates` flag is used, they will not be. In this case, we want to display the template parameter as part of the name. 
This change also adds comments to explain how regexps for shortening function names are used.

fix how template function names are simplified (follow-up to #498)

---

.travis.yml
appveyor.yml
go.mod
go.sum

Update travis config to tests both in GOPATH mode and modules mode.
While we are here, also update go versions used in travis-ci.

Add go.mod to the repository

---

internal/report/report.go

This allows averaging profiles by using:
pprof -proto output --divide_by <n> profile1.pb.gz ... profilen.pb.gz

Apply the --divide_by option to the profile before saving it.

---

internal/driver/driver_focus.go
internal/driver/driver_test.go

Tag filters like `-tagfilter=foo=1` currently cannot be used to filter
by a unitless numeric tag as the tag filter regular expression expects
the unit part to be always present.  They can be made working by using
`-tagfilter=foo=1unit` instead, but that's weird syntax. So fix this by
merely making the unit part optional.
I was wondering if this simple fix could have any unintended effects but
as far as I can tell from testing it does not.

Make tag filter of the form `-tagfilter=foo=1` work.

---

profile/proto.go

As per the vet check being introduced in 1.15
(https://github.com/golang/go/issues/32479), conversions of the form
string(int) are flagged by go vet. The suggested fix is to instead use
string(rune).
Additionally, since google/pprof is vendored into the go tree, we avoid
test failures from vet flagging this dependency (see
CL https://go-review.googlesource.com/c/go/+/220977).

profile: avoid string(int) conversion

---

profile/proto.go

The proto write type code stored in buffer stores unprintable values
(e.g. 2 when unmarshalling). The desired output when printing an error
message is the base-10 string representation of the integer (i.e. strconv.Itoa),
instead of the current behavior (string(int) or string(rune)), which return the
utf8 literal corresponding where the integer represents a unicode codepoint.
As pointed out by @ianlancetaylor in https://github.com/google/pprof/commit/4ac0da8#commitcomment-37524728,
commit 4ac0da8 preserves the previous incorrect behavior to pass a vet check,
whereas this change prints the desired output.
Updates golang/go#32479.

profile: change error message to print string representation of wire type

---

internal/driver/webhtml.go

This keeps the column names visible when scrolling down, which comes in
handy when there are many entries.

webhtml: make top table header sticky

---

profile/profile.go
profile/profile_test.go

CheckValid should check that all lines in locations have non nil function pointer.

profile.CheckValid should return an error if location has a line with empty function

---

internal/driver/fetch_test.go

Fixes: #526
Due to https://go.googlesource.com/go/+/2ff1e3e, the behavior changes to
> Providing the "seconds" parameter to other types of profiles is an error.

Remove the "seconds" parameter to fix tests.

---

.travis.yml

Since the release of go 1.14, go 1.12 is not supported any more: https://golang.org/doc/devel/release.html#policy.

Remove support for go 1.12 and add support for go 1.14 in Travis.

---

internal/driver/settings.go

Previously settingsFileName() created the ~/.config/pprof directory
if it did not exist. However, this is not possible for user nobody,
since its home directory is set to "/nonexistent". Instead, only
create the directory when we actually attempt to save the file, so
the error will happen at the appropriate interaction. This als
prevents pprof from creating empty settings directories.
Fixes the following error when running pprof's web UI as user nobody:
mkdir /nonexistent: permission denied

settings: Only call MkdirAll on save

---

.gitattributes

Fixes #551 
Ran ` git clone --single-branch --branch gitattribute git@github.com:wyk9787/pprof.git` and there is no uncommitted change.

Disable auto-converting line endings for non-text files.

---

internal/binutils/binutils.go
internal/binutils/binutils_test.go

Remove the extra version check to be compatible with different versions of GNU objdump (e.g. specialized version built internally within Google).

Remove extra version check on GNU objdump.

---

internal/graph/dotgraph.go
internal/graph/dotgraph_test.go
internal/graph/testdata/compose1.dot
internal/graph/testdata/compose2.dot
internal/graph/testdata/compose3.dot
internal/graph/testdata/compose4.dot
internal/graph/testdata/compose5.dot
internal/graph/testdata/compose6.dot
internal/report/report.go

Profile comments can have various special symbols which are then inserted as labels when generating graphs. If symbols are not escaped, graph generation can fail. This PR fixes that.

Escape labels when generating graph

---

.github/workflows/ci.yaml
.travis.yml

Fixes #566 
* Issues to address:
* Xcode version 10.3 has issue with macOS 10.15 in Github Action. See https://github.com/google/pprof/pull/560#issuecomment-699088881.
* We do not currently have a comprehensive coverage on different xcode / macOS versions.
* Existing limitations
* Github Action only supports macOS 10.15.
* Github Action doesn't support Golang master branch.
* Travis CI will time out if there are too many tests and there is no way to get around that.
* Travis CI cannot freely switch xcode and macOS version. They are bundled together as `osx_image`, see https://docs.travis-ci.com/user/reference/osx/.
* Solution
* Get rid of xcode 10.3 in Github Action.
* Support {xcode 10.3, macOS 10.14.4} and {xcode 11.3, macOS 10.14.6} with Golang = {1.13, 1.14, master} in Travis since …

Fix Github Action and modify supported xcode/macOS versions in both Github Action and Travis CI.

---

.github/workflows/ci.yaml

I saw failures in https://github.com/google/pprof/pull/559 that didn't seem related to my change, and wanted to be able to check if these tests had passed recently. Running our CI daily will allow us to do this.

chore: run Github Actions CI daily

---

internal/driver/tempfile.go
internal/driver/tempfile_test.go

The added test fails before the fix and passes after.
Fixes #500.

Fix a race in temp file creation.

---

internal/binutils/binutils_test.go

It seems objdump is not able to dump other architecture object.

Only run TestDisasm on amd64

---

go.mod
go.sum

Newer demangle version fixes bugs related to C++ templates

Update demangle dependency

---

internal/graph/graph.go
internal/graph/graph_test.go

Fixes #515.
Remove potential module path versions (v2, v3, v4, etc) from the input string before extracting a shortened name.  This makes it easier to tell which packages are which if the versions happen to match.
An example similar to my report:

Remove potential Go module versions from shortened names

---

internal/graph/graph.go

I changed to reuse seenEdge and seenNode.
I have a profile with 40,000 samples and each loop consumes a lot of time in allocating memory.
I avoided this by using the map-clearing range idiom.
benchmark:
```go
func BenchmarkNewGraph(b *testing.B) {
f, err := os.Open("testdata/a.pb.gz")
if err != nil {
b.Fatal(err)
}
defer f.Close()
p, err := profile.Parse(f)
if err != nil {
b.Fatal(err)
}
cfg := defaultConfig()
options := &plugin.Options{
UI:  &proftest.TestUI{},
Obj: fakeObjTool{},
}
_, r, err := generateRawReport(p, []string{"svg"}, cfg, options)
if err != nil {
b.Fatal(err)
}
b.ResetTimer()
for i := 0; i < b.N; i++ {
report.GetDOT(r)
}
}
```
result:
```
name        old time/op    new time/op    delta
NewGraph-8     2.38s ±10%     1.59s ± 8%  -33.01%  (p=0.000 n=10+10)
name        old …
```

feat: reuse seenEdge and seenNode to reduce garbage collection pressure

---

internal/driver/driver_test.go
internal/graph/dotgraph.go
internal/graph/dotgraph_test.go
internal/graph/testdata/compose3.dot
internal/graph/testdata/compose7.dot
internal/report/report_test.go

In some programming languages, e.g. JuliaLang, function names can contain arbitrary characters. For example, in julia, functions with non-identifier characters are represented via the string macro `var"..."`, which allows constructing identifiers that wouldn't otherwise parse.
These names are handled correctly by `pprof` in the FlameGraph view, but before this commit, they would produce an invalid dot file.
This fixes the dot graph export for names that contain `"`.
- All of the code changes are in the `internal/graph/dotgraph.go` file, and consist of escaping a few more callsites that produce text that will go in a string in the `.dot` file.
- The rest of the files are modifications to the tests:
1. We added a new test to test string escaping in the newly escaped parts of the `.dot` …

Add missing `escapeForDot()` to labels for function names

---

.github/workflows/ci.yaml

More specifically, we drop support for Xcode 11.0, 11.1 and add support for Xcode 12.1
Github Action supports the following Xcode versions: https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#xcode

Update supported Xcode versions to fix Github Action failures.

---

.github/workflows/ci.yaml

Context: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
This is resolved in setup-xcode's new version: https://github.com/maxim-lobanov/setup-xcode/issues/12#issuecomment-728796567

Update setup-xcode version to solve the deprecation issue.

---

.github/workflows/ci.yaml

Fixes #585. 
Workaround: Add `dot -c`, see https://gitlab.com/graphviz/graphviz/-/issues/1264.

Fix Github Action for Windows.

---

internal/driver/testdata/pprof.cpu.flat.addresses.weblist
internal/driver/webhtml.go
internal/report/source_html.go

When use pprof web ui, the source page header logo looks differ from other pages, but vertical centered.
fix other pages header logo looks.
other pages logo:
source page logo:
fixed other pages logo (vertical centered):

fix source page header logo looks.

---

internal/binutils/binutils.go

We were passing the wrong flag (--disassemble-all instead of
--disassemble). This mistake ended up generating bogus instruction
output by looking for covered addresses in non-executable sections
(e.g, we were finding data in the ".debug_info" section and
incorrectly interpreting it as instructions.

Fix wrong flag passed to objdump command when diassembling.

---

internal/binutils/addr2liner_llvm.go
internal/binutils/binutils.go
internal/binutils/binutils_test.go
internal/binutils/testdata/fake-llvm-symbolizer
internal/elfexec/elfexec.go
internal/elfexec/elfexec_test.go

This PR adds support for symbolizing virtual data addresses with the llvm-symbolizer. As a prerequisite, we have to compute the correct GetBase offset for data mappings, regardless of which local symbolizer is used. 
One of the commits, changes the current behavior from always computing a base offset relative to the executable program segment, to an approach that tries to identify the program segment associated with a given mapping and computing the offset relative to that segment. This change is enabled only for user space mappings. For kernel mappings, we continue to look for the kernel executable segment.
With this change, we drop support for fake mappings that span the entire address space. From an offline discussion with aalexand@:
- fake mappings were added by …

Enable symbolization of data objects with the llvm symbolizer

---

internal/elfexec/elfexec.go

Added text to specify that it can return a nil program header in some cases.

Update the function comment for FindProgHeaderForMapping.

---

internal/binutils/binutils.go

The fileNM structure does not need it as NM symbolization does not use the field.

Make isData field specific to fileAddr2Line.

---

internal/elfexec/elfexec.go
internal/elfexec/elfexec_test.go
profile/merge.go

In some cases, the loader maps the entire program address space in a single
runtime mapping that starts from the file offset of the first segment but
encompasses additional segments. Such mappings may be split later when
samples are detected in the following segments. However, a perf.data file
still includes the large initial mapping, which should be associated with
the first segment both before and after an eventual splitting. For each
segment, we compute the aligned file offset of its mapping assuming 4k page
alignment, and we filter out program segments that have aligned file
offsets greater than the given mapping file offset.

Handle large mappings in FindProgHeaderForMapping

---

profile/encode.go
profile/proto_test.go

By default, a numeric label with a value of zero is interpreted as an
empty label which will be ignored during parsing. However, a zero value
can be a valid label value. Instead of ignoring it altogether, parse it
as a zero-valued numeric label if num_unit is set.

Parse numeric labels with a value of zero if units are specified.

---

internal/binutils/binutils.go
internal/binutils/binutils_test.go

This change restores the old behavior in pprof of always  selecting
the executable segment  when computing the base for a mapping.
This is a temporary rollback, while we fix issues with the new segment
matching heuristic.

Disable segment selection for a mapping

---

driver/driver.go
internal/binutils/binutils.go
internal/binutils/binutils_test.go
internal/driver/driver_test.go
internal/driver/fetch_test.go
internal/driver/webui_test.go
internal/plugin/plugin.go
internal/report/report.go
internal/report/source.go
internal/symbolizer/symbolizer_test.go

Modify the plugin.ObjFile interface by replacing the "Base() uint64" method
with an "ObjAddr(addr uint64) (uint64, error)" method. The latter computes
the objdump address corresponding to the given runtime address.
The change removes direct access to the base value, but enables us to delay
computing the base until it is actually needed.

Replace Base() with ObjAddr() in the plugin.ObjFile interface.

---

internal/binutils/binutils.go
internal/binutils/binutils_test.go
internal/elfexec/elfexec.go
internal/elfexec/elfexec_test.go
internal/elfexec/testelf/testelf.go

We can use the sample's offset into the mapping to differentiate between small
segments that are in the same file page when associating a segment with the
mapping.

Delay base computation for ELF files until we have a sample address.

---

.github/workflows/ci.yaml

Fixes #625 
* Workflow run fails if any job fails: `continue-on-error = false` ([link](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error))
* Remaining matrix configurations keep running if one matrix configuration fails: `fail-fast = false` ([link](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast))
TESTED: Intentionally fail Go Tip on macOS https://github.com/wyk9787/pprof/actions/runs/797094911

Ensure the workflow run fail if any job fails, but remaining matrix configurations run if one matrix configuration fails.

---

internal/driver/testdata/pprof.cpu.flat.addresses.weblist
internal/report/source.go
internal/report/source_html.go
internal/report/source_test.go
internal/report/synth.go
internal/report/synth_test.go

Some profiles can contain locations without an address, or reference
binaries/libraries that are not available. Treat these better when
producing source listings by using any source information present
directly in the profile.Location.
Details:
If a location does not have an address, create a synthetic address
that does not fall in a known mapping.
If a location references an object file that is not found, use any
file/line information baked directly in the location.
Tweaked generated html to clicking for source lines that have no
inlining/assembly to display.

Source listing handles missing binaries and addresses.

---

internal/report/report.go
internal/report/report_test.go
internal/report/source.go

list, weblist, disasm, and peek all take a regexp argument that acts as
a filter.
Currently if this filter results in no matches we simply generate an
empty report, which can be confusing to users. Instead, explicitly treat
this as an error condition that is clearly reported to users.
Fixes #629

internal/report: error if filter argument has no matches

---

internal/binutils/binutils_test.go
internal/elfexec/elfexec.go
internal/elfexec/elfexec_test.go

Update the heuristic that matches mappings to segments to support split mappings.
The existing logic assumes a mapping is at least as large as the program segment. However, the loader, or some managing service, may split a program segment into multiple mappings for different reasons:
- to map part of the segment to huge pages, while other parts use regular sized pages;
- the last page may be remapped with write protection to zero out the bytes after the segment end in the last partial mapping page;
- if the segment includes both initialized and uninitialized data.
The list is not exhaustive. While https://github.com/google/perf_data_converter tries to combine associated split mappings into a single mapping, that heuristic also has limitations. Being able to match split mappings to …

Add support for matching split mappings to segments.

---

internal/binutils/addr2liner_llvm.go

The single dash -inlining is exotic.
Change it to the double-dash --inlining.
I removed most one-dash long options from llvm-symbolizer in
<https://reviews.llvm.org/D106377> (I forgot that pprof is still using
-inlining when I made the change.)
-demangle=false is also exotic but not changed. It is currently
implemented as a legacy alias
(llvm/llvm-project@c558c22cab9a555d2e521102b775759381e9727f).  We can
change it to --no-demangle once support for llvm-symbolizer < 9.0 is
dropped (https://reviews.llvm.org/D56773).

Change llvm-symbolizer to use --inlining

---

internal/elfexec/elfexec.go
internal/elfexec/elfexec_test.go

Segments with no file bits can have any file offset value, which can make them
appear to overlap other segments that start at those offsets.
This change prevents us from matching any mapping to such segments with zero
file content. But such segments would be loaded into anonymous mappings, which
we cannot symbolize anyway.

When matching mappings to segments, skip over segments with zero file size

---

.github/workflows/ci.yaml

Fixes #653 
`go get` is no longer supported outside a module, and we need to use `go install` to install executables, see https://golang.org/doc/go-get-install-deprecation for more details.
This PR also updated Go versions, macOS versions and their supported Xcode versions, and Linux versions.
TESTED: https://github.com/wyk9787/pprof/actions/runs/1288644610

Fix tests run by Github Action and update the testing matrix

---

internal/driver/commands.go
internal/driver/config.go
internal/driver/driver.go
internal/driver/tagroot.go
internal/driver/tagroot_test.go

These add synthetic stack frames to samples.
Example usage:
```
$ pprof -tagroot thread pprof.proto
```
Will add synthetic stack frames at the root like `thread:UIThread` and
`thread:BackgroundPool-1`.
Closes #558

Add -tagroot and -tagleaf options

---

.github/workflows/ci.yaml
test.sh

staticcheck only supports the latest 2 copmiler releases, not unreleased tip-of-tree versions.
Fixes #662.

ci: Disable staticcheck on tip-of-tree compiler.

---

internal/elfexec/elfexec.go

Not a functional change. Just separate a helper function to match most kernels heuristics.
This way they can be shared between ET_EXEC and ET_DYN kernels.
Tested: unit

Refactor GetBase heuristics for kernels.

---

internal/driver/testdata/pprof.cpu.flat.addresses.weblist
internal/report/source.go
internal/report/source_html.go

weblistPageClosing string ends in a new line, so printing it via fmt.Println will add an extra new line.

Avoid adding a redundant newline when printing weblistPageClosing

---

internal/report/source_test.go

Different versions of `objdump` output `call` or `callq`.
Both work fine for the purposes of the test.
Fixes #650

Update mapassign regex to match both call variants

---

proto/profile.proto

there is not "drop_functions" field in the proto.

proto/profile.proto: fix typo

---

CONTRIBUTING.md
README.md

Update instructions to use "git clone" instead of "go get".

---

README.md

Thought this might be useful to point people at the API docs (after I tried searching for pprof API docs and couldn't find them easily on Google).
Points at https://pkg.go.dev/github.com/google/pprof/profile, as that's the only package we try to declare as an API.
Badge generated at https://pkg.go.dev/badge/?path=https%3A%2F%2Fpkg.go.dev%2Fgithub.com%2Fgoogle%2Fpprof%2Fprofile

Add badge link to Go API docs in pkg.go.dev

---

internal/symbolizer/symbolizer.go

This helps diagnose symbolization issues.

Log build ID in local symbolization error messages.

---

internal/graph/dotgraph.go
internal/graph/dotgraph_test.go
internal/graph/testdata/compose9.dot

The first comment in a pprof file is used as the subgraph ID for the
legend, but was not escaped. If the comment contained double quotes,
it could cause graphviz to fail to parse the output, or to render
incorrect graphs. To reproduce, run the following commands:
```
$ pprof -add_comment "unterminated \"double quote" -proto -output=bug.pprof in.pprof
Generating report in labels-no-specials-unterminated-double-quote.pprof
$ pprof -comments bug.pprof
unterminated "double quote
$ pprof -web bug.pprof
Error: <stdin>: syntax error in line 3 near '\'
pprof: failed to execute dot. Is Graphviz installed? Error: exit status 1
```
Add a test for this case. Without the change to dotgraph.go, the test
produced the following dot output:
```
digraph "testtitle" {
node [style=filled fillcolor="#f8f8f8"] …
```

internal/graph: Support comments with double quotes

---

.github/workflows/ci.yaml

Like Go itself, pprof supports two latest major versions of Go. Since
1.18 was released, we should add it and drop 1.16.

Add Go 1.18 to testing, remove Go 1.16.

---

internal/driver/tagroot.go
internal/driver/tagroot_test.go

It's possible for the unit array to be empty for a unitless numeric tag.
In this case the tag value should be formatted properly but before this
change it was output empty.
Fixes #651. From the bug description it doesn't look like exactly this
issue but it does get fixed.
The added tests fail before the change and pass after.

Fix tagroot to properly format unitless numeric tags.

---

internal/graph/graph_test.go
profile/legacy_profile.go

https://github.com/golang/go/issues/51082 changed how gofmt handles some
comments, so we need to slightly reformat them to avoid `gofmt -s -d .`
errors.

Fix doc comments format to become compatible with tip gofmt.

---

go.mod

pprof follows the Golang version policy and currently that mean
supporting 1.17 and 1.18. We've been following that in the CI
configuration, but go.mod has been lagging behind for a while.

Update minimum Go version to 1.17 in go.mod.

---

internal/driver/webui_test.go

Different environments may have compiled flamegraph JS code
differently. Generalize regular expression that checks
generated code to allow some variation.

Made flamegraph test less brittle.

---

internal/driver/settings.go
internal/driver/settings_test.go

An earlier change had added support for placing pprof URLs under
the /ui prefix. However config menu entry URLs were built by
editing a URL produced by stripping the /ui prefix and were
therefore falling outside the /ui prefix. This ended up in
mis-navigation to the graph view when a config menu entry was
selected in another view.
Fixed by emitting a relative URL (e.g., ?f=foo) instead of an
absolute URL (e.g., /flamegraph?f=foo).

Make config menu entries relative.

---

internal/graph/dotgraph.go
internal/graph/graph_test.go
internal/symbolizer/symbolizer.go
internal/symbolizer/symbolizer_test.go

This PR fixes two issues:
1. Demangle detects Go symbols with type parameters as C++ symbols and strips out parentheses (e.g., `main.(*Foo[...]).Method` -> `main..Method`.
2. Dot conversion replaces `.` with newlines, converting `[...]` -> `[\n\n\n]`.
See individual commit messages for more details.
Fixes #705

Improve handling of Go symbols with type parameters

---

doc/README.md
internal/driver/html/common.css
internal/driver/html/common.js
internal/driver/html/header.html
internal/driver/html/stacks.css
internal/driver/html/stacks.html
internal/driver/html/stacks.js
internal/driver/stacks.go
internal/driver/webhtml.go
internal/driver/webui.go
internal/driver/webui_test.go
internal/report/package.go
internal/report/package_test.go
internal/report/report_test.go
internal/report/shortnames.go
internal/report/shortnames_test.go
internal/report/stacks.go
internal/report/stacks_test.go

Add an experimental flame-graph implementation. It can be selected in
pprof's web interface using the new "Flame (experimental)" menu entry.
At some point this new implementation may become the default.
The new view is similar to flame-graph view. But it can show caller
information as well. This should allow it to satisfy many users of
Graph and Peek views as well.
Let's illustrate with an example. Suppose we have profile data that
consists of the following stacks:
```
1000	main -> foo -> malloc
2000	main -> bar -> malloc
```
When main is selected, both the old and new views show:
```
[-------------------3000 main---------------------]
[---1000 foo-----] [----------2000 bar------------]
[---1000 malloc--] [----------2000 malloc---------]
```
But suppose now the user selects the right-most …

Added alternative flamegraph implementation that can show callers.

---

doc/README.md
internal/driver/html/stacks.css
internal/driver/html/stacks.js
internal/report/report_test.go
internal/report/stacks.go
internal/report/stacks_test.go

Mark frames sent to javascript with a boolean "Inlined" field. Use
this field to change the display by (1) adding an "(inlined)" marker
to the tooltip for the frame, and (2) by dropping any border between
the caller and the caller.
Document flame graph display, including coloring and visual indication
of inlining.

Add visual indication of inlined frames.

---

internal/driver/cli.go
internal/driver/fetch.go
internal/driver/fetch_test.go

This protocol is already supported by various tools and lldb. e.g.: https://github.com/llvm-mirror/lldb/blob/d01083a850f577b85501a0902b52fd0930de72c7/source/Symbol/LocateSymbolFile.cpp#L311
Among others it is used by Fuchisa OS builds.
This change was unit tested with `fetch_test.go`.
It was manually tested with a FuchsaOS build by pointing pprof at `$FUCHSIA_HOME/out/default/.build-id`

Add new symbol directory layout by build-id `/xx/xxxxxxxx.debug`.

---

internal/driver/fetch.go

This makes it more convenient to profile jobs with many replicas. Per offline discussion with aalexand, we prefer to just raise the limit rather than adding another config knob.

Increase chunk size for concurrent fetch to 128

---

internal/driver/driver.go

This is similar in spirit to #393. By default this flag is not set, but if it's specified on the command line it's better to respect the value.
This addresses b/259563268.

Apply -noinlines flag to the proto output.

---

internal/driver/webui_test.go

"go vet" (at tip) caught a use of a loop variable in a go routine inside the loop. This is not thread-safe since the loop variable value can change while the go routine is active.

Fix use of captured loop variable in go routine.

---

internal/driver/fetch.go

When users specify the path to the main binary on the command line as an easy way to make pprof find it, there is a possibility to make a mistake and point to a wrong version of the binary. This will break symbolization in unpredictable ways. I think we should only insert the build ID if it is not present in the profile.

Do not overwrite main binary build ID when it's present.

---

internal/graph/graph.go
internal/graph/graph_test.go

Names like foo/xyz are not Go names but match the current regular expression. Modify it to require a dot to be present for the Go shortening to trigger.
This should fix b/262922429.

Modify the name shortening heuristic to handle non-Go names

---

internal/driver/cli.go
internal/driver/fetch.go

Look for debug symbols in all locations GDB does (https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html)
, e.g.:
- /usr/lib/debug/.build-id/ab/cdef1234.debug
- /usr/bin/binary.debug
- /usr/bin/.debug/binary.debug
- /usr/lib/debug/usr/bin/binary.debug.
My use case is development for embedded devices using Yocto. There I get a rootfs which I boot on target, and a rootfs-dbg with all debug symbols in `/usr/lib/debug/path/to/file.debug`. I record data with tcmalloc on target, and run pprof on that data after copying it to my development host. This change (specifically option 4 from the list below) lets me point `PPROF_BINARY_PATH=/path/to/rootfs-dbg/`, and find debug symbols for my application and all shared libraries it uses.
Option 1 from the list above is already implemented, …

Extend search for debug symbols

---

.github/workflows/ci.yaml

Hi! 👋🏻
The `ci` Github Actions in the repo is using deprecated runtimes for its workflows. I've upgraded the deprecated actions to versions that uses non-deprecated runtimes.
Note that `setup-go@v4` will try to enable caching unless the `cache` input is explicitly set to false. I'll be more than happy to make it false if wanted. 
Open to feedback if there are any other changes wanted done regarding Github Actions 😄

chore(ci): Upgrade to non-deprecated runtimes

---

profile/encode.go

Just a small change to save an allocation in `postDecode()` function.
```
BenchmarkKernelRelocationSymbol-12    	154684881	         7.796 ns/op	       0 B/op	       0 allocs/op
BenchmarkKernelRelocationSymbol-12    	23326599	        49.38 ns/op	       8 B/op	       1 allocs/op
```

Get rid of strings.ReplaceAll to save an allocation

---

internal/driver/cli.go

I am not entirely sure why this heuristic exists and we have -buildid flag for this anyway. I suspect having this shortcut to specify the build ID was for some reason more important in the past (more profiles did not record the build ID of the main binary? not sure), but now it seems very exotic to have to specify the build ID anyway.

Remove the heuristic of recognizing build ID command line arg.

---

internal/driver/fetch.go
internal/driver/fetch_test.go

url.Parse can parse a Windows absolute path without problems.
This can cause mapping file to be cleared, even though it's not a
remote source.
For #710

internal/driver: fixes for fetch.go

---

.github/workflows/ci.yaml

Also add using https://github.com/re-actors/alls-green to enforce a check that all CI jobs pass. This will ease configuring this in the GitHub project settings since before this we had to update that list manually with a lot of clicking every time the test matrix changes.

Update macOs matrix since macos-10.15 is deprecated and unavailable.

---

doc/README.md
internal/driver/html/stacks.css
internal/driver/html/stacks.js

Previously, the self cost part of a flame graph box  was shown with a tweaked color.
```
[<-- self --><-- rest of the cost -->]
[child 1][child2][child3]
```
However this added clutter and was too subtle (I asked a couple of colleagues and they hadn't noticed it).
This change removes this coloring. The self cost is still available in the tooltip for each box and is also visible as the area to the left of the first child.

Remove special coloring for self region in new flame graph view.

---

doc/README.md
internal/driver/html/common.js
internal/driver/html/header.html
internal/driver/webui.go
internal/driver/webui_test.go

In preparation for removing the dependency on D3 make the new flamegraph view the default. The old view is still available under /flamegraphold for now.

Made non-D3 flamegraph view the default.

---

go.mod
go.sum
internal/binutils/disasm.go
internal/symbolizer/symbolizer.go

github.com/ianlancetaylor/demangle now has new
`demangle.NoEnclosingParams` option that enables stripping the parameters of a lambda's enclosing function, similar to how regular functions' names are simplified with the `demangle.NoParams` option pprof already uses.
E.g. we currently get
`foo_namespace::BarMethod(SomeArgType*)::$_0::operator()`, and with the new option it will be `foo_namespace::BarMethod::$_0::operator()`.
It seems the right thing to start using that option: If there is a function with a loop and then that loop is turned into an algorithm function call with a lambda, it doesn't seem right that the name of that lambda function suddenly gets parameters unstripped compared to the straight loop version.
This is part of b/284684693.

Start using the new demangle.NoEnclosingParams demangling option.

---

.github/dependabot.yml
.github/workflows/ci.yaml

Fixes #786.
As described in the issue, this PR hash-pins all workflow Actions to protect the project from supply-chain attacks.
I've also set up dependabot to monitor the GitHub Actions. Whenever a new version is released, you'll receive a PR updating the Action's hash and the associated version comment.

Hash-pin workflow Actions

---

doc/README.md
internal/driver/html/stacks.css
internal/driver/html/stacks.js

Previously, the flamegraph display was broken in the presence of `--diff_base` because it did not account for the fact that some stacks could have negative values.  This change fixes the handling of negative values by tracking two numbers per displayed box that covers a set of stacks:
1. `sumpos`: the sum of the absolute values of increases in the stacks.
2. `sumneg`: the sum of the absolute values of decreases in the stacks.
The width of the box is proportional to `sumpos + sumneg`.
In addition, if a box has an overall decrease (`sumneg > sumpos`), the fraction of the box corresponding to the decrease is shaded green. (Similarly part of the box is shaded red if the box has an overall increase.)
Changed the display of legends and tooltips to clearly show the added and removed samples. …

Fix flamegraph display in the presence of --diff_base.

---

internal/driver/html/common.js
internal/driver/html/header.html

Previously, we would use the sample type name as the HTML id for the corresponding menu entry. However some profiles contain sample type names that conflict with other HTML ids we use (in particular, the sample type name "sample" conflicted with a different id). Remove this name clash by prefixing every menu entry with "sampletype-".
some profiles caused the Javascript to break bec

Prefix sample type menu entry ids with "sampletype-".

---

internal/driver/html/common.js
internal/driver/html/stacks.js
internal/report/stacks.go

Previously, we were using the same regexp to match both a node's FunctionName (for server-side filtering) and UniqueName (for browser-side pivoting). However the two strings can differ (UniqueName can end with a #<number> in case of overloads). This resulted in us being unable to ignore/focus/hide overloaded functions.
We now use distinct regexps for the two different use cases.  And we no longer compute the regexps in Go. Instead we do this in Javascript using the pre-existing quotemeta function.
The quotemeta function has now been moved to the top-level and renamed to pprofQuoteMeta.

Fix flamegraph name matching.

---

.github/workflows/ci.yaml

https://github.com/golang/go/commit/de4d50316fb5c6d1529aa5377dc93b26021ee843 dropped support for "go get" in GOPATH mode.
Remove the GOPATH based test execution in our Github workflow since it will not work reliably any more.

Remove GOPATH based workflows since Go is reducing support.

---

internal/driver/browser_test.go
internal/driver/testdata/testfixture.js
internal/driver/testdata/testflame.js

We now do some rudimentary testing of the flamegraph web interface. The test code is written in Javascript and uses a simple test fixture class.

Add initial flamegraph web interface test.

---

internal/driver/html/stacks.js
internal/driver/testdata/testflame.js

Previously, we would pass an invalid 'f' URL parameter when switching from the new Flamegraph view to another view if nothing was selected. We now check for this case and avoid the bad behavior.
Also added a test for this behavior.
Fixes #812.

Fix broken URL parameters in new flame graph menus.

---

.github/workflows/ci.yaml

1) Golang is now at 1.21, so add 1.21 and drop 1.19.
2) xcode 11.7 on macOS 11 CI builds have been broken recently, failing
with error
```
Warning: You are using macOS 11.
We (and Apple) do not provide support for this old version.
...
Error: Your Xcode (11.7 => /Applications/Xcode_11.7.app/Contents/Developer) is too outdated.
Please update to Xcode 13.2.1 (or delete it).
Xcode can be updated from the App Store.
```
Reading https://en.wikipedia.org/wiki/MacOS_Big_Sur, it says that
macOS 11 is unsupported as of September 26, 2023, so let's drop
xcode 11.7 and macOS 11.

Update golang, macOS and xcode versions.

---

.github/workflows/ci.yaml

I noticed the `ci.yml` workflow uses `honnef.co/go/tools/cmd/staticcheck@master` and mentions that it should be replaced by a specific version once an issue in that dependency is fixed.
It was fixed earlier this year, in [release 0.4.1](https://github.com/dominikh/go-tools/releases/tag/2023.1.1). This PR adopts the latest release version (0.4.6). Let me know if you'd rather just use 0.4.1.

Use a release version of staticcheck in `ci.yml`

---

internal/driver/fetch.go
internal/driver/fetch_test.go

Fixes https://github.com/google/pprof/issues/816

Fix exception when file type contains colon

---

internal/symbolizer/symbolizer.go

This allows only keeping a single objfile open to reduce the amount of consumes memory.

Handle one file at a time in local symbolization.

---

internal/driver/browser_test.go
internal/driver/html/stacks.js
internal/driver/testdata/testflame.js

The Javascript code now behave the same as the Go code. (It switches to the next unit only if one unit is at least as big as the value being displayed.) The main effect is that we no longer use "hours" as the unit for time values in the range [36s,3600s). We only switch to using "hours" when the measured time is at least one hour. This is easier for users to understand: e.g., a time value of hundred seconds now displays as "100s", not "0.03hrs".
Also added a unittest for the Javascript unit picking code.

Flamegraph uses seconds instead of hours when appropriate.

---

internal/driver/html/stacks.html
internal/driver/html/stacks.js
internal/driver/stacks.go
internal/driver/testdata/testflame.js
internal/driver/webui.go
internal/measurement/measurement.go

Go unit definitions (from measurement package) are now converted to JSON and delivered to Javascript code so that we do not need to duplicate these definitions in Javascript.
Had to make the unit type definitions exported with public fields.
Also had to change a test case to expect "us" instead of "µs".

Share unit definitions between Go and Javascript.

---

profile/profile.go

The //anon mappings do not correspond to an actual file so pprof trying to look them up on disk and complaining with a warning is not useful.

Assume //anon files unsymbolizable.

---

internal/graph/graph.go

I was running github actions to run linter [makezero](https://github.com/ashanbrown/makezero) for top github golang repos.
see issues https://github.com/alingse/go-linter-runner/issues/1
and the github actions output https://github.com/alingse/go-linter-runner/actions/runs/9241873083/job/25423942721 
```
====================================================================================================
append to slice `nodes` with non-zero initialized length at https://github.com/google/pprof/blob/main/internal/graph/graph.go#L44[9](https://github.com/alingse/go-linter-runner/actions/runs/9241873083/job/25423942721#step:4:10):11
====================================================================================================
```

fix: fix miss makezero bug

---

internal/driver/html/stacks.js

Previously, the click handler would fire after some text was selected with the mouse. This would switch pivots and forget the selected text.
We now switch the pivot only if the mouse did not move significantly between mouse-down and mouse-up.
Fixes #870.

Allow text selection in flamegraph view.

---

internal/driver/html/common.css
internal/driver/html/stacks.css

Previously the profile details box (displayed when clicking button at top-right of web view), would partially overlap flame graph text. Tweak z-index values to fix this problem.
Also, colocate all z-index CSS entries to make the stacking order of different things easier to compare.

Fix stacking order of profile details box.

---

internal/driver/stacks.go
internal/report/report.go
internal/report/stacks.go
internal/report/stacks_test.go

Previously, we used to call report.TextItems() during flame graph generation just so we could get a hand on the legend to print in the profile details box. All the work done by TextItems() to produce a trimmed graph was discarded.
This change separates out the legend generation into a separate routine so that we can avoid doing the unnecessary work.
Benchmark result:
```
name      old time/op  new time/op  delta
Flame-12   6.10s ± 3%   0.39s ± 4%  -93.59%  (p=0.000 n=10+10)
```

Speed-up flame graph generation by skipping unneeded work.

---

internal/binutils/addr2liner_llvm.go
internal/binutils/testdata/fake-llvm-symbolizer

In some edge cases (e.g. injected JIT symbols), function names can have
new lines. This breaks the llvm-symbolizer output parsing, and makes
pprof hang.
Conveniently, as of LLVM 13, llvm-symbolizer has a JSON output mode,
which is robust against all kinds of weirdness like new lines. We can
use this instead of the line-based parsing, and as a bonus we get much
simpler handling of multiple frames in a stack, as the JSON output
already returns these as an array.
This also requires splitting the CODE and DATA processing into separate
functions, since their JSON output is incompatible. For now, we keep the
DATA output as before, a slightly hacky but functional concatenation of
start + size, but this could be improved.

Use llvm-symbolizer's JSON output for symbolizing

---

internal/report/report.go
internal/report/report_test.go

Output looks something like:
```
% pprof -top ...
File: ...
Build ID: ...
Type: cpu
Doc: http://example.com/cpuprofile
Duration: 6.71s, Total samples = 5.72s (85.30%)
Showing nodes accounting for 5.17s, 90.38% of 5.72s total
Dropped 326 nodes (cum <= 0.03s)
...
```

Added doc link to profile header.

---

internal/driver/html/stacks.css
internal/driver/html/stacks.html
internal/driver/html/stacks.js

Display the details (name + samples) of the currently hovered box above the flame graph. If no box is currently being hovered over, we display the total samples in the flame graph.
Fixes #836.

Display hovered box details immediately.

---

internal/report/report.go
internal/report/report_test.go

The current time format (Jan 2, 2006 at 3:04pm (MST)) has a few issues:
- It displays time at minute granularity, while profiles usually have have second-level (and more[^go]) granularity.
- It uses a 12-hour clock, which is tricky to handle at AM/PM switchovers, for people (like myself) who are not used to it. By contrast, a 24-hour clock is unambiguous.
- Minor: using names for months makes it more difficult to calculate with time differences.
Hence, I propose replacing it with an RFC3339-alike format, with spaces between elements for better readability.
[^go]: https://github.com/golang/go/blob/3aa71c12eacd68ec16e7172d92aa5c6af32f0c3b/src/runtime/pprof/proto.go#L351

tui: use RFC3339-alike format with second precision for "Time"

---

internal/symbolz/symbolz.go

We added skipping unsymbolizable mappings in symbolz long time ago in PR #368 to address #339 where we saw error like "unexpected negative adjusted address".
But that error was fixed in a more proper way in subsequent #397 to fix another reported issue #280 (and internal b/32020573). So skipping unsymbolized mappings shouldn't be needed anymore.
I tested this by verifying that the test case from #339 still works fine with the proposed change. And that it does fail if I roll back #397 locally.
This change is useful as we experiment with using symbolz to symbolize JIT locations from //anon (which is unsymbolizable per current terminology).

Allow symbolz to try symbolize unsymbolizable mappings.

---

internal/driver/html/stacks.js

With this patch, it's possible to navigate from the (new and now only) flame graph to the source code for a box.

Fix 'show source [in new tab]' under -lines

---

internal/symbolizer/symbolizer.go

Avoid trying to demangle functions one by one; besides, `demangleSingleFunction` doesn't quite behave correctly when **no** demangling is requested.

Bail out fast when no demangling is requested

---

internal/symbolizer/symbolizer.go
internal/symbolizer/symbolizer_test.go

See discussion at https://github.com/google/pprof/issues/477#issuecomment-2600988101

handle demangling OSX names with underscore prefix

---

internal/driver/html/common.css

The canvas used to scale itself to the aspect ratio of the full graph, which might be fairly wide. That means even while zooming, the original aspect ratio is preserved and only a 'letterbox' is shown.
This CSS change fixes that.
Fixes: #835

Fix canvas to fill the full height.
